package com.xworkz.encapsulation;

import com.xworkz.encapsulation.dto.ShopDto;

public class ShopDtoRunner {

	public static void main(String[] args) {
		
		ShopDto obj = new ShopDto("Stoppers Shop","Hassaan","Provision Store","Ulaga",4,3000000,50000,100000,50000,6,1,"2 in a Month",15000,300000,"Ramu","Varun","Rice",1500,"oil",150);
	    System.out.println(obj);	 
	    
	    obj.setShopName("Stoppers Shop");
	    obj.setAddress("Hassaan");
	    obj.setType("Provision Store");
	    obj.setOwner("Ulaga");
	    obj.setWorkers(4);
	    obj.setMonthyIncome(3000000);
	    obj.setDailyExpenses(50000);
	    obj.setDailyIncome(100000);
	    obj.setDailySavings(50000);
	    obj.setOpenDays(6);
	    obj.setOffDay(1);
	    obj.setWorkersLeave("2 in a Month");
	    obj.setShpoRent(15000);
	    obj.setShopDeposit(300000);
	    obj.setWorkerName("Ramu");
	    obj.setCashierName("Varun");
	    obj.setMostSellingItem("Rice");
	    obj.setItemPrice(1500);
	    obj.setItemName("oil");
	    obj.setPrice(150);
	    obj.setOilName("Sunpure");
	    obj.setSellsVegitables(true);
	    obj.setSellsFruits(true);
	    obj.setTomatoPerKg(20);
	    obj.setOnionPerKg(30);
	    obj.setLemonPerPiece(5);
	    obj.setCucumberPerKg(60);
	    obj.setGreenPeas(80);
	    obj.setBeans(60);
	    obj.setCabbage(100);
	    obj.setGreenChilly(60);
	    obj.setCapcicum(80);
	    obj.setApple("Kashmiri Apple");
	    obj.setApplePrice(200);
	    obj.setPineapple("PineApple");
	    obj.setPineapplePrice(40);
	    obj.setPamogranate("Pamogranate");
	    obj.setPamoPrice(150);
	    obj.setGrapes("Green Grapes");
	    obj.setGrapesPrice(100);
	    obj.setChicoo("Chicoo");
	    obj.setChicooPrice(140);
	    obj.setGuava("Guava");
	    obj.setGuavaPrice(100);
	    obj.setBiscuiteName("Hide & Seek");
	    obj.setBiscuitePrice(20);
	    obj.setCoolDrink("7UP");
	    obj.setIceCreame("Butter Scotch");
	    obj.setPacketMasala("Chicken Masala");
	    obj.setMasalaPrice(10);
	    obj.setPencils("Apsara");
	    obj.setPricePerPencil(5);
	    obj.setPricePerPen(10);
	    obj.setPens("Writo Meter");
	    obj.setCigerattes("Wills Premium Flake");
	    obj.setPricePerPack(90);
	    obj.setBeedi("Ganesh Beedi");
	    obj.setPricePerBundle(25);
	    obj.setEggs("Eggs");
	    obj.setPricePerEgg(6);
    
	    System.out.println(obj.getShopName());
	    System.out.println(obj.getAddress());
	    System.out.println(obj.getType());
	    System.out.println(obj.getOwner());
	    System.out.println(obj.getWorkers());
	    System.out.println(obj.getMonthyIncome());
	    System.out.println(obj.getDailyExpenses());
	    System.out.println(obj.getDailyIncome());
	    System.out.println(obj.getDailySavings());
	    System.out.println(obj.getOpenDays());
	    System.out.println(obj.getOffDay());
	    System.out.println(obj.getWorkersLeave());
	    System.out.println(obj.getShpoRent());
	    System.out.println(obj.getShopDeposit());
	    System.out.println(obj.getWorkerName());
	    System.out.println(obj.getCashierName());
	    System.out.println(obj.getmostSellingItem());
	    System.out.println(obj.getItemPrice());
	    System.out.println(obj.getItemName());
	    System.out.println(obj.getPrice());
	    System.out.println(obj.getOilName());
	    System.out.println(obj.getSellsVegitables());
	    System.out.println(obj.getSellsFruits());
	    System.out.println(obj.getTomatoPerKg());
	    System.out.println(obj.getOnionPerKg());
	    System.out.println(obj.getLemonPerPiece());
	    System.out.println(obj.getCucumberPerKg());
	    System.out.println(obj.getGreenPeas());
	    System.out.println(obj.getBeans());
	    System.out.println(obj.getCabbage());
	    System.out.println(obj.getGreenChilly());
	    System.out.println(obj.getCapcicum());
	    System.out.println(obj.getApple());
	    System.out.println(obj.getApplePrice());
	    System.out.println(obj.getPineapple());
	    System.out.println(obj.getPineapplePrice());
	    System.out.println(obj.getPamogranate());
	    System.out.println(obj.getPamoPrice());
	    System.out.println(obj.getGrapes());
	    System.out.println(obj.getGrapesPrice());
	    System.out.println(obj.getChicoo());
	    System.out.println(obj.getChicooPrice());
	    System.out.println(obj.getGuava());
	    System.out.println(obj.getGuavaPrice());
	    System.out.println(obj.getBiscuiteName());
	    System.out.println(obj.getBiscuitePrice());
	    System.out.println(obj.getCoolDrink());
	    System.out.println(obj.getIceCreame());
	    System.out.println(obj.getPacketMasala());
	    System.out.println(obj.getMasalaPrice());
	    System.out.println(obj.getPencils());
	    System.out.println(obj.getPricePerPencil());
	    System.out.println(obj.getPricePerPen());
	    System.out.println(obj.getPens());
	    System.out.println(obj.getCigerattes());
	    System.out.println(obj.getPricePerPack());
	    System.out.println(obj.getBeedi());
	    System.out.println(obj. getPricePerBundle());
	    System.out.println(obj.getEggs());
	    System.out.println(obj. getPricePerEgg());
	}

}
